Unit/iss#16/testing
gerish01/MLE-Training pull request #17
Opened 2024-03-29 07:14 UTC by gerish01

fixes #16 

 This PR sets up Unit-Testing-Workflow using GitHub Actions.

2024-03-29 10:03 UTC, sarath-srinivas requested changes
Please do not write any logic in the unit tests. The tests only mock some inputs and call a function from the package and check the output. There is lot of logic in your unit tests. Only if the logic is reused from the module, the test makes sense, otherwise the logic in test is not  indicative of the logic in the modules..

2024-03-29 10:44 UTC, gerish01 commented
Okay sir, Will change it

2024-03-29 18:26 UTC, gerish01 commented
Hi sir,
I have made the necessary corrections.
I have revised the unit tests accordingly, removed any unnecessary logic from the tests
Thank You sir

2024-04-01 05:15 UTC, sarath-srinivas approved these changes

2024-04-01 05:17 UTC, merged